"""Learned per-entrypoint `est_minutes` defaults — the estimate feedback loop.

Spec: docs/specs/est-defaults.spec.md (resolves calibration.spec Q3).

Two roles:
  * **Producer** (this file's CLI / `main`): reconstruct historical successful-run durations from the
    registry (reusing `calibration.py`'s read + reconstruction, READ-ONLY), derive a per-entrypoint
    `est_minutes = ceil(p90 of done-task active_minutes)`, and write the committed sidecar
    `fleet/est_defaults.json`.
  * **Consumer** (`load_default` / `resolve_est_minutes`, imported by `runq.py`): supply that value when
    `runq add --est-minutes` is omitted; an explicit `--est-minutes` always overrides.

    python fleet/est_defaults.py [--db D] [--since ISO] [--min-sample N] [--dry-run] [--out F]

Determinism (spec invariant 6): same (db, since, min_sample) => byte-identical sidecar. No wall-clock or
RNG in the written bytes (`sort_keys=True`, no timestamp field).
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))  # sibling imports (fleet isn't a pkg)

import registry_db  # noqa: E402
import calibration  # noqa: E402  (reuse read + reconstruction, READ-ONLY)

# Site data: `<FLEET_SITE_DIR>/est_defaults.json` when a site directory is named (registry_db.site_file).
SIDECAR = registry_db.site_file("est_defaults.json", Path(__file__).resolve().parent / "est_defaults.json")
DEFAULT_MIN_SAMPLE = 5
STATISTIC = "ceil(p90) of done-task non-degenerate active_minutes"


# --------------------------------------------------------------------------- derive (pure)

def derive_defaults(actuals, min_sample: int) -> dict:
    """Pure: TaskActuals -> the sidecar doc (minus the DB-path `_meta` fields the caller fills).

    Invariant 1: population is `done` state, non-degenerate (>= DEGENERATE_FLOOR_MIN) only.
    Invariant 2: per entrypoint, est_minutes = max(1, ceil(p90(active_minutes))); median is informational.
    Invariant 3: low_confidence = n < min_sample (still emitted, still usable).
    """
    by_ep: dict[str, list[float]] = {}
    contributing = 0
    for a in actuals:
        if a.state != "done" or a.degenerate:
            continue
        by_ep.setdefault(a.entrypoint, []).append(a.active_minutes)
        contributing += 1

    entries: dict[str, dict] = {}
    for ep in sorted(by_ep):
        mins = sorted(by_ep[ep])
        n = len(mins)
        median = calibration.percentile(mins, 0.50)
        p90 = calibration.percentile(mins, 0.90)
        entries[ep] = {
            "est_minutes": max(1, math.ceil(p90)),
            "n": n,
            "actual_median": calibration._round(median, 1),
            "actual_p90": calibration._round(p90, 1),
            "low_confidence": n < min_sample,
        }
    return {
        "_meta": {
            "min_sample": min_sample,
            "generated_task_count": contributing,
            "statistic": STATISTIC,
        },
        "entrypoints": entries,
    }


# --------------------------------------------------------------------------- live (in-flight) arm

LIVE_MIN_SAMPLE = 3
LIVE_PERCENTILE = 0.90


def learn_group_estimates(rows, min_sample: int = LIVE_MIN_SAMPLE,
                          percentile: float = LIVE_PERCENTILE) -> dict:
    """Pure: [(entrypoint, grp, actual_minutes)] -> {(entrypoint, grp): est_minutes}.

    The IN-FLIGHT half of the feedback loop (invariant 24). The committed sidecar above keys on
    `entrypoint` and is regenerated by hand; that was adequate when an entrypoint WAS a workload,
    and is now the wrong key. Measured 2026-07-31 on `native.training.m49_curriculum_ab` (1182 done
    tasks / 14d): one entrypoint spans 270 groups whose runtimes range p10 6 min -> median 33 ->
    p90 182. A single per-entrypoint p90 is therefore 5.5x the median task and 29x the p10 task —
    i.e. keying on entrypoint alone MANUFACTURES the over-estimation it exists to remove.

    GROUP is the predictive key, and cheaply so: within-group sd 31 min vs between-group sd 81 min
    over the 90 groups with n>=5. A group is one campaign/sweep, whose cells differ by a knob and
    run for similar lengths — so once a few cells finish, the REST of that campaign can be estimated
    from its own siblings. That is what makes this automatic: no CLI, no commit, no restart, and it
    self-corrects inside the campaign that is currently mis-estimated.

    `percentile` stays p90 (not median) for the reason the sidecar uses it: over-estimation wastes
    budget, under-estimation causes hard-cap eviction and stall-reap, so the loop is deliberately
    asymmetric. `min_sample` guards against setting a campaign's estimate from one fast outlier."""
    by_key: dict[tuple, list[float]] = {}
    for entrypoint, grp, minutes in rows:
        if minutes is None or minutes <= 0:
            continue
        by_key.setdefault((entrypoint, grp), []).append(float(minutes))
    out: dict[tuple, int] = {}
    for key, mins in by_key.items():
        if len(mins) < min_sample:
            continue
        out[key] = max(1, math.ceil(calibration.percentile(sorted(mins), percentile)))
    return out


def _dumps(doc: dict) -> str:
    return json.dumps(doc, indent=2, sort_keys=True)


def write_defaults(path, doc: dict) -> None:
    """Deterministic write (invariant 6): sorted keys, indent=2, trailing newline."""
    Path(path).write_text(_dumps(doc) + "\n")


# --------------------------------------------------------------------------- read glue

def read_actuals(db_path, group=None, entrypoint=None, since=None, now=None):
    """READ-ONLY (invariant 9): reuse calibration's connect/fetch/reconstruct. Returns TaskActuals."""
    conn = calibration._connect_ro(db_path)
    try:
        tasks, events, _instances = calibration._fetch(conn, group, entrypoint, since)
    finally:
        conn.close()
    now = now or datetime.now(timezone.utc)
    by_task: dict = {}
    for e in events:
        by_task.setdefault(e["task_id"], []).append(e)
    return [calibration.reconstruct_task_actuals(t, by_task.get(t["id"], []), now) for t in tasks]


# --------------------------------------------------------------------------- consumer (runq.py)

def load_default(entrypoint: str, path=None):
    """Return the persisted est_minutes for `entrypoint`, else None. Never raises (invariant 10/12):
    a missing/malformed sidecar or a non-positive-int entry yields None."""
    p = Path(path) if path is not None else SIDECAR
    try:
        doc = json.loads(p.read_text())
        v = doc["entrypoints"][entrypoint]["est_minutes"]
    except (OSError, json.JSONDecodeError, KeyError, TypeError):
        return None
    # bool is an int subclass; reject it explicitly. Only a positive int is a valid learned default.
    if isinstance(v, bool) or not isinstance(v, int) or v <= 0:
        return None
    return v


def resolve_est_minutes(explicit, entrypoint: str, loader=load_default):
    """runq add resolution (invariant 5). Returns (value, source in {'explicit','learned'}).
    Raises ValueError when no value can be resolved (caller -> exit 2)."""
    if explicit is not None:
        if explicit <= 0:
            raise ValueError("--est-minutes must be > 0")
        return explicit, "explicit"
    learned = loader(entrypoint)
    if learned is None:
        raise ValueError(f"--est-minutes required (no learned default for {entrypoint})")
    return learned, "learned"


# --------------------------------------------------------------------------- CLI

def _print_table(doc: dict, stream=sys.stdout) -> None:
    eps = doc["entrypoints"]
    stream.write(f"est_minutes recommendations (min_sample={doc['_meta']['min_sample']}, "
                 f"statistic={doc['_meta']['statistic']}):\n")
    if not eps:
        stream.write("  (no eligible done tasks)\n")
        return
    stream.write(f"  {'entrypoint':<22} {'n':>4} {'median':>8} {'suggest':>8}  flag\n")
    for ep in sorted(eps):
        r = eps[ep]
        flag = "LOW-CONF" if r["low_confidence"] else ""
        stream.write(f"  {ep:<22} {r['n']:>4} {r['actual_median']:>8} "
                     f"{r['est_minutes']:>8}  {flag}\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Derive per-entrypoint est_minutes defaults from history.")
    ap.add_argument("--db", default=None, help="registry db (default: shared experiments root)")
    ap.add_argument("--since", default=None, help="ISO8601; only tasks with created_at >=")
    ap.add_argument("--min-sample", type=int, default=DEFAULT_MIN_SAMPLE,
                    help=f"below this n, flag low_confidence (default {DEFAULT_MIN_SAMPLE})")
    ap.add_argument("--dry-run", action="store_true", help="print only; do not write the sidecar")
    ap.add_argument("--out", default=None, help=f"sidecar path (default {SIDECAR})")
    args = ap.parse_args(argv)

    db_path = args.db or str(registry_db.shared_experiments_root() / "runs.sqlite")
    out_path = args.out or str(SIDECAR)

    actuals = read_actuals(db_path, since=args.since)
    doc = derive_defaults(actuals, args.min_sample)
    doc["_meta"]["generated_from"] = Path(db_path).name
    doc["_meta"]["since"] = args.since

    _print_table(doc)
    if args.dry_run:
        sys.stdout.write(_dumps(doc) + "\n")
        return 0

    write_defaults(out_path, doc)
    print(f"wrote {len(doc['entrypoints'])} entrypoints to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
